core/urls.py
from django.urls import path, include


from . import views


app_name = 'core'

urlpatterns = [
    path('export/', views.ExportView.as_view(), name='export'),
    path('player/filter/', views.PlayerFilterView.as_view(), name='player-filter-view'),
    path('players/<int:pk>/', views.PlayerView.as_view(), name='player-stats-view'),
    path('players/', views.PlayersListView.as_view(), name='players-view'),
    path('teams/<int:pk>/rushing', views.TeamRushingStatsView.as_view(), name='team-rushing-stats-view'),
    path('teams/<int:pk>/', views.TeamStatsView.as_view(), name='team-stats-view'),
    path('teams/', views.TeamsListView.as_view(), name='teams-view'),
    path('', views.HomeView.as_view(), name='home-view'),
]

stats/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("select2/", include("django_select2.urls")),
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.cache import cache
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


POSITIONS = (
    ('RB', _("Runningback")),
    ('QB', _("Quarterback")),
    ('WR', _("Wide Receiver")),
    ('FB', _("Fullback")),
    ('P', _("Punter")),
    ('TE', _("Tightend")),
    ('NT', _("Nose Tackle")),
    ('DB', _("Defensiveback")),
    ('SS', _("Strong Safety")),
    ('K', _("Kicker"))
)


CONFERENCES = (
    ('AFC', _("AFC")),
    ('NFC', _("NFC"))
)

DIVISIONS = (
    ('N', _("North")),
    ('S', _("South")),
    ('E', _("East")),
    ('W', _("West"))
)


class STATS_CACHE_MIXIN(object):
    def get_cached_stat(self, key, q, timeout, order_by=None):
        stats = cache.get(key)
        if not stats:
            stats = self.season_stats.filter(q)
            if order_by:
                stats = stats.order_by(order_by)
            cache.set(key, stats, timeout=timeout)
        return stats


class Franchise(models.Model):
    name = models.CharField(max_length=255, help_text="The name of the overall organization")


class Season(models.Model):
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    current = models.BooleanField(default=False)

    def __str__(self):
        if self.start_date.year == self.end_date.year:
            return '{}'.format(self.start_date.year)
        return '{}/{}'.format(self.start_date.strftime('%y'), self.end_date.strftime('%y'))

    @classmethod
    def get_current_season(cls):
        return Season.objects.get(current=True)


class Player(STATS_CACHE_MIXIN, models.Model):
    name = models.CharField(max_length=255, help_text="The full name of the player.")
    position = models.CharField(max_length=255, choices=POSITIONS, help_text="The player's position")

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return '{} - {}'.format(self.name, self.position)

    def get_current_season_stats(self):
        key = 'current-season-player-stats-{}'.format(self.id)
        if not hasattr(self, '_current_season_stats'):
            q = Q(season__current=True)
            self._current_season_stats = self.get_cached_stat(key, q, settings.PLAYER_STATS_TIMEOUT)
        return self._current_season_stats

    def get_previous_seasons_stats(self):
        key = 'previous-season-player-stats-{}'.format(self.id)
        if not hasattr(self, '_previous_season_stats'):
            q = Q(season__current=False)
            order_by = 'season__start_date'
            self._previous_season_stats = self.get_cached_stat(key, q, settings.PLAYER_STATS_TIMEOUT, order_by=order_by)
        return self._previous_season_stats


class Team(STATS_CACHE_MIXIN, models.Model):
    name = models.CharField(max_length=255, help_text="The long form team name (ex. Seattle Seahawks)")
    abbreviation = models.CharField(max_length=255, help_text="The abbreviation of the team (ex. SEA)")
    nfl_com_link = models.CharField(max_length=255, help_text="The nfl.com team website address.")
    alternate_abbreviation = models.CharField(max_length=255, help_text="The alternate/newer  abbreviation of the team (ex. LAC)")
    conference = models.CharField(max_length=255, choices=CONFERENCES, help_text="The division the team is currently in.")
    division = models.CharField(max_length=255, choices=DIVISIONS, help_text="The division the team is currently in.")

    def __str__(self):
        return '{} ({})'.format(self.name, self.abbreviation)

    @property
    def logo_url(self):
        abbr = self.alternate_abbreviation or self.abbreviation
        url = 'https://static.www.nfl.com/league/api/clubs/logos/{}.svg'.format(abbr)
        return url

    def get_current_season_stats(self):
        key = 'current-season-team-stats-{}'.format(self.id)
        if not hasattr(self, '_current_season_stats'):
            q = Q(season__current=True)
            self._current_season_stats = self.get_cached_stat(key, q, settings.TEAM_STATS_TIMEOUT)
        return self._current_season_stats

    def _get_season_stats_ordered(self, filter):
        return self.get_current_season_stats().order_by(filter)

    def get_current_season_rushing_attempts_leader(self):
        return self._get_season_stats_ordered('-attempts').first()

    def get_current_season_rushing_yards_leader(self):
        return self._get_season_stats_ordered('-yards').first()

    def get_current_season_rushing_touchdowns_leader(self):
        return self._get_season_stats_ordered('-touchdowns').first()

    def get_current_season_rushing_1st_leader(self):
        return self._get_season_stats_ordered('-first_down').first()

    def _get_total_rushing_stats(self):
        key = 'rushing-yards-{}{}{}'.format(self.conference, self.division, self.abbreviation)
        current_stats = cache.get(key)
        if not current_stats:
            # current_season = Season.get_current_season()
            # current_stats = PlayerSeasonStats.objects.filter(team=self, season=current_season)
            # post coding session
            current_stats = self.season_stats.filter(season__current=True)
            cache.set(key, current_stats, timeout=settings.TEAM_STATS_TIMEOUT)
        return current_stats

    def get_total_rushing_stats(self):
        current_stats = self._get_total_rushing_stats()
        return sum([stat.yards for stat in current_stats])

    def test(self):
        cs = self._get_total_rushing_stats()
        lc = [stat.yards for stat in cs]
        return self.calc(lc)

    def calc(self, lc):
        total = sum(lc)
        return total / len(lc)

    def get_average_rushing_stats(self):
        current_stats = self._get_total_rushing_stats()
        total = sum([stat.yards for stat in current_stats])
        num = len(current_stats)
        return total / num

    def get_avg_avg_stats(self):
        current_stats = self._get_total_rushing_stats()
        total = sum([stat.average for stat in current_stats])
        num = len(current_stats)
        return total / num
        
    @classmethod
    def get_conference_division_teams(cls, conference_teams, division):
        conference = ''
        if conference_teams:
            conference = conference_teams.first().conference
        key = 'divison-teams-{}{}'.format(conference, division)
        division_teams = cache.get(key)
        if not division_teams:
            division_teams = conference_teams.filter(division=division)
            cache.set(key, division_teams, timeout=settings.TEAM_STATS_TIMEOUT)
        return division_teams

    @classmethod
    def get_conference_teams(cls, conference):
        key = 'conference-teams-{}'.format(conference)
        conference_stats = cache.get(key)
        if not conference_stats:
            conference_stats = cls.objects.filter(conference=conference)
            cache.set(key, conference_stats, timeout=settings.TEAM_STATS_TIMEOUT)
        return conference_stats


class PlayerSeasonStats(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='season_stats')
    season = models.ForeignKey(Season, on_delete=models.CASCADE, related_name='season_stats')
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='season_stats')
    attempts = models.PositiveIntegerField(default=0)
    attempts_game = models.FloatField(default=0)
    yards = models.IntegerField(default=0)
    average = models.FloatField(default=0)
    yards_game = models.FloatField(default=0)
    touchdowns = models.PositiveIntegerField(default=0)
    longest_gains = models.IntegerField(default=0)
    longest_gains_touchdown = models.BooleanField(default=False)
    first_down = models.PositiveIntegerField(default=0)
    first_down_conversion = models.FloatField(default=0)
    twenty_plus = models.PositiveIntegerField(default=0)
    forty_plus = models.PositiveIntegerField(default=0)
    fumbles = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ('player__position', 'player__name')

core/forms.py
from django import forms


class TableSortForm(forms.Form):
    longest_gains = forms.IntegerField()
    touchdowns = forms.IntegerField()
    yards = forms.IntegerField()

core/views.py
import csv

from unicodedata import category
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView, DetailView, View
from django.db.models import Count
from django.http import HttpResponseRedirect, HttpResponse 
from django.urls import reverse
from django.utils import timezone
from django.core.cache import cache

from .models import Team, Player, PlayerSeasonStats, Season
from .forms import TableSortForm


def generate_order_by(cleaned_data):
    gains = cleaned_data['longest_gains'] 
    yards = cleaned_data['yards'] 
    touchdowns = cleaned_data['touchdowns'] 
    order_by = []
    lng_sort = 'longest_gains'
    yds_sort = 'yards'
    td_sort = 'touchdowns'
    if yards == 1:
        order_by.append(yds_sort)
    elif yards == 2:
        order_by.append('-{}'.format(yds_sort))
    if touchdowns == 1:
        order_by.append(td_sort)
    elif touchdowns == 2:
        order_by.append('-{}'.format(td_sort))
    if gains == 1:
        order_by.append(lng_sort)
    elif gains == 2:
        order_by.append('-{}'.format(lng_sort))
    return order_by


class SORT_MIXIN(object):
    def sort_queryset(self, qs, form):
        if form.is_valid():
            order_by = generate_order_by(form.cleaned_data)
            qs = qs.order_by(*order_by)
        return qs

class HomeView(TemplateView):
    template_name = 'core/home.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['current_season_stats'] = Season.get_current_season().season_stats
        self.request.session['player_filter'] = None
        return ctx


class TeamsListView(ListView):
    model = Team

    def get_queryset(self):
        return self.model.objects.none()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        self.request.session['player_filter'] = None
        ctx['afc_teams'] = self.model.get_conference_teams('AFC')
        ctx['nfc_teams'] = self.model.get_conference_teams('NFC')
        return ctx


class TeamRushingStatsView(ListView):
    model = Team
    template_name = 'core/team_rushing_stats.html'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.order_by('name')
        return qs



class TeamStatsView(SORT_MIXIN, DetailView):
    model = Team

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        current_season_stats = self.get_object().get_current_season_stats()
        form = TableSortForm(self.request.GET or None)
        ctx['lng'] = 0
        ctx['yds'] = 0
        ctx['tds'] = 0
        self.request.session['player_filter'] = None
        if form.is_valid():
            current_season_stats = self.sort_queryset(current_season_stats, form)
            cleaned_data = form.cleaned_data
            ctx['lng'] = cleaned_data['longest_gains'] 
            ctx['yds'] = cleaned_data['yards'] 
            ctx['tds'] = cleaned_data['touchdowns'] 
        ctx['current_season_stats'] = current_season_stats
        return ctx


class PlayersListView(SORT_MIXIN, ListView):
    model = PlayerSeasonStats
    template_name = 'core/player_list.html'
    paginate_by = 25

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(season__current=True).order_by('player__name')
        player_filter = self.request.session.get('player_filter', None)
        if player_filter:
            qs = qs.filter(player__name__icontains=player_filter)
        order_by = self.build_order_by()
        if len(order_by) > 0:
            qs = qs.order_by(*order_by)
        return qs

    def build_order_by(self):
        form = TableSortForm(self.request.GET or None)
        order_by = []
        if form.is_valid():
            order_by = generate_order_by(form.cleaned_data)
        return order_by

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        form = TableSortForm(self.request.GET or None)
        current_season_stats = self.get_queryset()
        ctx['lng'] = 0
        ctx['yds'] = 0
        ctx['tds'] = 0
        ctx['export_sort'] = True
        if form.is_valid():
            cleaned_data = form.cleaned_data
            ctx['lng'] = cleaned_data['longest_gains'] 
            ctx['yds'] = cleaned_data['yards'] 
            ctx['tds'] = cleaned_data['touchdowns'] 
        return ctx


class PlayerView(DetailView):
    model = Player
    template_name = 'core/player_details.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['current_season_stats'] = self.get_object().get_current_season_stats()
        ctx['previous_season_stats'] = self.get_object().get_previous_seasons_stats()
        return ctx


class PlayerFilterView(TemplateView):
    template_name = 'core/player_list.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        player_name = self.request.GET.get('player_name', None)
        if player_name:
            self.request.session['player_filter'] = player_name
        return ctx

    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        return HttpResponseRedirect(reverse('core:players-view'))


class ExportView(View):
    def get(self, request, *args, **kwargs):
        response = HttpResponse(
            content_type='text/csv',
            headers={'Content-Disposition': 'attachment; filename="export_{}.csv"'.format(timezone.now())},
        )
        writer = csv.writer(response)
        
        qs = PlayerSeasonStats.objects.filter(season__current=True).order_by('player__name')
        player_filter = self.request.session['player_filter']
        if player_filter:
            qs = qs.filter(player__name__icontains=player_filter)
            
        form = TableSortForm(self.request.GET or None)
        if form.is_valid():
            order_by = generate_order_by(form.cleaned_data)
            qs = qs.order_by(*order_by)
        else:
            qs = qs.order_by('player__name')
        
        for result in qs:
            td = '*' if result.longest_gains_touchdown else ''
            longest_gains = '{}{}'.format(result.longest_gains, td)
            writer.writerow([result.player.name,
                             result.player.position,
                             result.team.name,
                             result.attempts,
                             result.attempts_game,
                             result.yards,
                             result.average,
                             result.yards_game,
                             result.touchdowns,
                             longest_gains,
                             result.first_down,
                             result.first_down_conversion,
                             result.twenty_plus,
                             result.forty_plus,
                             result.fumbles])

        return response

core/templates/core/widgets/_conference_teams.html
{% load core_tags %}

<h4 class="mt-4">North</h4>
{% include "core/widgets/_division_teams.html" with teams=teams|division_teams:"N" %}

<h4 class="mt-4">South</h4>
{% include "core/widgets/_division_teams.html" with teams=teams|division_teams:"S" %}

<h4 class="mt-4">East</h4>
{% include "core/widgets/_division_teams.html" with teams=teams|division_teams:"E" %}

<h4 class="mt-4">West</h4>
{% include "core/widgets/_division_teams.html" with teams=teams|division_teams:"W" %}

core/templates/core/widgets/_division_teams.html
<div class="row row-cols-md-5 row-col-6">
    {% for team in teams %}
    <a href="{% url 'core:team-stats-view' team.id %}" class="card-anchor">
        <div class="col">
            <div class="card h-100 text-center">
                <img src="{{ team.logo_url }}" class="card-img-top img-responsive">
                <h5 class="mt-1 card-title">{{ team.name }}</h5>
            </div>
        </div>
    </a>
    {% endfor %}
</div>

core/templates/core/widgets/_player_stats_table_row.html
{% with player=stat.player %}
{% with team=stat.team %}
<tr>
    {% if show_player_info %}
    <td><a href="{% url 'core:player-stats-view' player.pk %}">{{ player.name }}</a></td>
    <td>{{ player.position }}</td>
    {% if show_team_logo %}<td><a href="{% url 'core:team-stats-view' team.id %}"><img src="{{ team.logo_url }}" style="width:25px;" /></a></td>{% endif %}
    {% elif show_season_info %}
    <td>{{ stat.season }}</td>
    {% endif %}
    <td>{{ stat.attempts }}</td>
    <td>{{ stat.attempts_game }}</td>
    <td>{{ stat.yards }}</td>
    <td>{{ stat.average }}</td>
    <td>{{ stat.yards_game }}</td>
    <td>{{ stat.touchdowns }}</td>
    <td>{{ stat.longest_gains }}{% if stat.longest_gains_touchdown %}*{% endif %}</td>
    <td>{{ stat.first_down }}</td>
    <td>{{ stat.first_down_conversion }}</td>
    <td>{{ stat.twenty_plus }}</td>
    <td>{{ stat.forty_plus }}</td>
    <td>{{ stat.fumbles }}</td>
</tr>
{% endwith %}
{% endwith %}

core/templates/core/widgets/_stat_leader_showcase_detail.html
{% if show_player_image %}<a href="{% url 'core:player-stats-view' player.id %}">{% endif %}
    <div class="col">
        <h5>{{ title }} </h5>
        <div class="card">
            {% if show_player_image %}
            <div class="card-img-top text-center p-2">
                <i class="fas fa-user" style="font-size:15em;"></i>
            </div>
            {% endif %}
            <div class="card-body">
                {% if show_player_image %}
                <div class="card-text d-flex flex-row justify-content-center"><h4>{{ player.name }}</h4></div>
                {% endif %}
                <div class="card-text d-flex flex-row justify-content-center"><h5>{{ stat }}</h5></div>
            </div>
        </div>
    </div>
{% if show_player_image %}</a>{% endif %}

core/templates/core/widgets/_stats_leader_showcase.html
{% load i18n core_tags %}

{% translate "Attempts" as attempts_title %}
{% with attempts_stat=stats|rushing_attempts_leader %}
{% include 'core/widgets/_stat_leader_showcase_detail.html' with title=attempts_title player=attempts_stat.player stat=attempts_stat.attempts show_player_image=show_player_image %}
{% endwith %}

{% translate "Yards" as yards_title %}
{% with yards_stat=stats|rushing_yards_leader %}
{% include 'core/widgets/_stat_leader_showcase_detail.html' with title=yards_title player=yards_stat.player stat=yards_stat.yards show_player_image=show_player_image  %}
{% endwith %}

{% translate "Touchdowns" as touchdowns_title %}
{% with touchdowns_stat=stats|rushing_touchdowns_leader %}
{% include 'core/widgets/_stat_leader_showcase_detail.html' with title=touchdowns_title player=touchdowns_stat.player stat=touchdowns_stat.touchdowns show_player_image=show_player_image  %}
{% endwith %}

{% translate "1st Downs" as first_down_title %}
{% with first_down_stat=stats|rushing_1st_leader %}
{% include 'core/widgets/_stat_leader_showcase_detail.html' with title=first_down_title player=first_down_stat.player stat=first_down_stat.first_down show_player_image=show_player_image  %}
{% endwith %}

core/templates/core/widgets/_stats_table.html
{% load i18n %}

{% if request.session.player_filter %}
<input type="hidden" name="player_name" value="{{ request.session.player_filter  }}">
{% endif %}
<div {% if sortable %}id="sortable-table"{% endif %}>
    <div class="row mb-4">
        <div class="col border-bottom d-flex justify-content-between"><h5>{{ title }}</h5>
            <button v-show="sorted" class="btn btn-sm btn-primary float-right mb-2">Apply Sort</button>
        </div>
    </div>
    <div class="row">
        <div class="col-12"> 
            <table class="table table-dark table-sm table-striped">
                <tr>
                    {% if show_player_info %}
                    <th>{% translate "Player Name" %}</th>
                    <th>{% translate "Position" %}</th>
                    {% if show_team_logo %}
                    <th>{% translate "Team" %}</th>
                    {% endif %}
                    {% elif show_season_info %}
                    <th>{% translate "Season" %}</th>
                    {% endif %}
                    <th>ATT</th>
                    <th>ATT/G</th>
                    {% if sortable %}
                    <th v-on:click="ydsClick">YDS
                        <input :value="yds" type="hidden" name="yards">
                        <span v-show="yds === 1"><i class="fas fa-sort-up"></i></span>
                        <span v-show="yds === 2"><i class="fas fa-sort-down"></i></span>
                    </th>
                    {% else %}
                    <th>YDS</th>
                    {% endif %}
                    <th>AVG</th>
                    <th>YDS/G</th>
                    {% if sortable %}
                    <th v-on:click="tdsClick">TD
                        <input :value="tds" type="hidden" name="touchdowns">
                        <span v-show="tds === 1"><i class="fas fa-sort-up"></i></span>
                        <span v-show="tds === 2"><i class="fas fa-sort-down"></i></span>
                    </th>
                    {% else %}
                    <th>TDS</th>
                    {% endif %}
                    {% if sortable %}
                    <th v-on:click="lngClick">LNG
                        <input :value="lng" type="hidden" name="longest_gains">
                        <span v-show="lng === 1"><i class="fas fa-sort-up"></i></span>
                        <span v-show="lng === 2"><i class="fas fa-sort-down"></i></span>
                    </th>
                    {% else %}
                    <th>LNG</th>
                    {% endif %}
                    <th>1st</th>
                    <th>1st%</th>
                    <th>20+</th>
                    <th>40+</th>
                    <th>FUM</th>
                </tr>
                {% for stat in stats %}
                {% include 'core/widgets/_player_stats_table_row.html' with stat=stat show_player_info=show_player_info show_team_logo=show_team_logo %}
                {% empty %}
                <tr>
                    <td colspan="15" class="text-center pt-2 "><h5>No previous stats</h5></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>


{% block extrascript %}
{% if sortable %}
<script>
    var preload = {
        lng: {{ lng }},
        yds: {{ yds }},
        tds: {{ tds }},
    };
</script>
{% endif %}
{% endblock %}